runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /www/img
  static_dir: www/img

- url: /www/icons
  static_dir: www/icons

- url: /www/cv
  static_dir: www/cv

- url: /.*
  script: main.app
  secure: always
